name: 'Todoist: Create Task'
author: 'Mickaël Allonneau'
description: 'Creates a task in Todoist'

inputs:
  task-name:
    description: 'The name of the task'
    required: true
  todoist-api-token:
    description: 'The Todoist API token of the account to create the task in'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Create request body JSON file
      shell: bash
      env:
        TASK_NAME: ${{ inputs.task-name }}
      run: |
        touch request-body.json
        echo '{"content": "'"$TASK_NAME"'"}' >> request-body.json
    
    - name: Run cURL command
      shell: bash
      env:
        TODOIST_API_TOKEN: ${{ inputs.todoist-api-token }}
      run: >
        curl "https://api.todoist.com/rest/v2/tasks"
        -X POST
        -d @request-body.json
        -H "Content-Type: application/json"
        -H "X-Request-Id: $(uuidgen)"
        -H "Authorization: Bearer $TODOIST_API_TOKEN"
