name: 'Todoist: Create Task'
author: 'Mickaël Allonneau'
description: 'Creates a task in Todoist'

# Inputs' descriptions are taken from the official Todoist API doc: https://developer.todoist.com/rest/v2/#create-a-new-task
inputs:
  task-name:
    description: "Task content [or name]. This value may contain markdown-formatted text and hyperlinks. Details on markdown support can be found in the Text Formatting article in [Todoist's] Help Center."
    required: true
  todoist-api-token:
    description: 'The Todoist API token of the account to create the task in.'
    required: true
  task-priority:
    description: 'Task priority from 1 (normal) to 4 (urgent).'
    required: false
  task-project-id:
    description: "Task project ID. If not set, task is put to user's Inbox."
    required: false
  task-section-id:
    description: 'ID of section to put task into.'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Create cURL request's JSON body
      env:
        TASK_NAME: ${{ inputs.task-name }}
        TASK_PRIORITY: ${{ inputs.task-priority }}
        TASK_PROJECT_ID: ${{ inputs.task-project-id }}
        TASK_SECTION_ID: ${{ inputs.task-section-id }}
      shell: bash
      run: $GITHUB_ACTION_PATH/create-curl-request-json-body.sh

    - name: Run cURL command
      env:
        TODOIST_API_TOKEN: ${{ inputs.todoist-api-token }}
      shell: bash
      run: >
        curl "https://api.todoist.com/rest/v2/tasks"
        -X POST
        -d @curl-request-body.json
        -H "Authorization: Bearer $TODOIST_API_TOKEN"
        -H "Content-Type: application/json"
        -H "X-Request-Id: $(uuidgen)"