name: 'README: Update Inputs / Outputs tables'
on: [workflow_dispatch]

jobs:
  update-readme:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update README
        uses: mdvorak/update-action-readme@v1

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: readme-inputs-outputs-update-${{ github.ref_name }}
          commit-message: "readme: update inputs / outputs tables"
          title: "README: Update Inputs / Outputs on ${{ github.ref_name }}"
